// Generated by .NET Reflector from e:\IT Management\1397\Projects\تردد کامیون\Karabin (002)\KarabinEmbeddedLPRLibrary\Karabin.Embedded.LPR.Library.dll
namespace KarabinEmbeddedLPRLibrary
{
    using System;
    
    internal class Constants
    {
        public static string[] CharlettersIndex;
        public static string[] CharlettersIndexNedap;

        static Constants()
        {
            string[] strArray = new string[] { "الف", "ب", "س", "د", "ع", "ق", "ه", "ج", "ل" };
            strArray[9] = "م";
            strArray[10] = "ن";
            strArray[11] = "ص";
            strArray[12] = "ط";
            strArray[13] = "و";
            strArray[14] = "ت";
            strArray[15] = "ی";
            strArray[16] = "ژ";
            strArray[17] = "پ";
            CharlettersIndex = strArray;
            strArray = new string[] { "A", "B", "C", "D", "E", "G", "H", "J", "L" };
            strArray[9] = "M";
            strArray[10] = "N";
            strArray[11] = "S";
            strArray[12] = "T";
            strArray[13] = "V";
            strArray[14] = "X";
            strArray[15] = "Y";
            strArray[16] = "Z";
            strArray[17] = "P";
            CharlettersIndexNedap = strArray;
        }
    }
}
